module Names exposing (..)

names =
    [ "aerified"
    , "alpha"
    , "alphazap"
    , "andalax"
    , "asoka"
    , "bamity"
    , "bigtax"
    , "biodex"
    , "bitchip"
    , "bitwolf"
    , "bytecard"
    , "cardguard"
    , "cardify"
    , "cookley"
    , "daltfresh"
    , "domainer"
    , "fintone"
    , "fixflex"
    , "gembucket"
    , "holdlamis"
    , "home ing"
    , "it"
    , "kanlam"
    , "keylex"
    , "konklab"
    , "latlux"
    , "lotlux"
    , "lotstring"
    , "mat lam tam"
    , "namfix"
    , "opela"
    , "otcom"
    , "overhold"
    , "pannier"
    , "prodder"
    , "quo lux"
    , "redhold"
    , "regrant"
    , "ronstring"
    , "solarbreeze"
    , "sonair"
    , "sonsing"
    , "span"
    , "stronghold"
    , "subin"
    , "tampflex"
    , "temp"
    , "tempsoft"
    , "toughjoyfax"
    , "transcof"
    , "treeflex"
    , "tres-zap"
    , "tresom"
    , "trippledex"
    , "vagram"
    , "ventosanzap"
    , "viva"
    , "voltsillam"
    , "wrapsafe"
    , "y-find"
    , "y-solowarm"
    , "zaam-dox"
    , "zontrax"
    ]
